Update ns-label-check.yaml

diff --git a/.github/workflows/ns-label-check.yaml b/.github/workflows/ns-label-check.yaml
--- a/.github/workflows/ns-label-check.yaml
+++ b/.github/workflows/ns-label-check.yaml
@@ -31,6 +31,7 @@ jobs:
             if grep -q "kind: Namespace" "$file"; then
               if grep -q "istio.io/rev" "$file"; then
                 echo "comment=Error,istio.io/rev label found" >> $GITHUB_OUTPUT
+                echo "Error: istio.io/rev label found in "$file"" | tee -a out.txt
               fi
             fi
           done
@@ -47,9 +48,6 @@ jobs:
           ```
 
     - name: Fail if any istio labels present
-      env:
-        COMMENT: ${{ steps.check.outputs.comment }}
+      if: steps.check.outputs.comment
       run: |
-        if grep Error $COMMENT > /dev/null 2>&1; then 
-          exit 1
-        fi
+        exit 1
